<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ECM.Application\ECM.Application.csproj" />
      <ProjectReference Include="..\ECM.Data\ECM.Data.csproj" />
      <ProjectReference Include="..\ECM.Domain\ECM.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Catalogo\category\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Catalogo\category\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Catalogo\category\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Catalogo\category\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Catalogo\category\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\category\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\category\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\category\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\category\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\category\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Coupon\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Coupon\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Coupon\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Coupon\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Coupon\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Coupon\Validate.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Review\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Review\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Review\Detailss.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Review\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Review\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Review\ProductReviews.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Review\UserReviews.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Shipment\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Shipment\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Shipment\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Shipment\EditStatus.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Shipment\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Logistica\Shipment\Track.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Views\Catalogo\category\Create.cshtml" />
      <UpToDateCheckInput Remove="Views\Catalogo\category\Delete.cshtml" />
      <UpToDateCheckInput Remove="Views\category\Create.cshtml" />
      <UpToDateCheckInput Remove="Views\category\Delete.cshtml" />
      <UpToDateCheckInput Remove="Views\Catalogo\category\Create.cshtml" />
      <UpToDateCheckInput Remove="Views\Catalogo\category\Delete.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Views\category\Details.cshtml" />
      <AdditionalFiles Include="Views\category\Index.cshtml" />
      <AdditionalFiles Include="Views\product\Create.cshtml" />
    </ItemGroup>
    
    
    
</Project>
