<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DTO\Catalogo\" />
      <Folder Include="DTO\Logistica\" />
      <Folder Include="DTO\Ventas\" />
      <Folder Include="Mappers\Catalogo\" />
      <Folder Include="Mappers\Identidades\" />
      <Folder Include="Mappers\Logistica\" />
      <Folder Include="Mappers\Ventas\" />
      <Folder Include="Services\Catalogo\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ECM.Domain\ECM.Domain.csproj" />
    </ItemGroup>

</Project>
