<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Repositories\Catalogo\" />
      <Folder Include="Repositories\Identidades\" />
      <Folder Include="Repositories\Logistica\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ECM.Application\ECM.Application.csproj" />
      <ProjectReference Include="..\ECM.Domain\ECM.Domain.csproj" />
    </ItemGroup>

</Project>
